#!/usr/bin/env bash
# One-time setup: S3 bucket + DynamoDB table for Terraform remote state (CI/CD).
#
# Usage:
#   export AWS_REGION=us-west-2
#   bash infra/ci/bootstrap-state.sh
#
# Then add GitHub secrets TF_STATE_BUCKET and TF_STATE_LOCK_TABLE (printed at end).
# For local dev: cp infra/envs/dev/backend.hcl.example infra/envs/dev/backend.hcl
# and run: cd infra/envs/dev && terraform init -backend-config=backend.hcl -migrate-state

set -euo pipefail

REGION="${AWS_REGION:-us-west-2}"
ACCOUNT_ID="$(aws sts get-caller-identity --query Account --output text)"
BUCKET="${TF_STATE_BUCKET:-netknife-tfstate-${ACCOUNT_ID}}"
TABLE="${TF_STATE_LOCK_TABLE:-netknife-tfstate-lock}"

echo "==> Region: ${REGION}"
echo "==> Account: ${ACCOUNT_ID}"
echo "==> State bucket: ${BUCKET}"
echo "==> Lock table: ${TABLE}"

if aws s3api head-bucket --bucket "$BUCKET" 2>/dev/null; then
  echo "Bucket already exists: ${BUCKET}"
else
  echo "Creating S3 bucket..."
  if [ "$REGION" = "us-east-1" ]; then
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION"
  else
    aws s3api create-bucket --bucket "$BUCKET" --region "$REGION" \
      --create-bucket-configuration "LocationConstraint=${REGION}"
  fi
  aws s3api put-bucket-versioning --bucket "$BUCKET" \
    --versioning-configuration Status=Enabled
  aws s3api put-bucket-encryption --bucket "$BUCKET" \
    --server-side-encryption-configuration '{"Rules":[{"ApplyServerSideEncryptionByDefault":{"SSEAlgorithm":"AES256"}}]}'
  aws s3api put-public-access-block --bucket "$BUCKET" \
    --public-access-block-configuration BlockPublicAcls=true,IgnorePublicAcls=true,BlockPublicPolicy=true,RestrictPublicBuckets=true
  echo "Created bucket: ${BUCKET}"
fi

if aws dynamodb describe-table --table-name "$TABLE" --region "$REGION" >/dev/null 2>&1; then
  echo "DynamoDB table already exists: ${TABLE}"
else
  echo "Creating DynamoDB lock table..."
  aws dynamodb create-table \
    --table-name "$TABLE" \
    --attribute-definitions AttributeName=LockID,AttributeType=S \
    --key-schema AttributeName=LockID,KeyType=HASH \
    --billing-mode PAY_PER_REQUEST \
    --region "$REGION"
  aws dynamodb wait table-exists --table-name "$TABLE" --region "$REGION"
  echo "Created table: ${TABLE}"
fi

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
BACKEND_HCL="${PROJECT_ROOT}/infra/envs/dev/backend.hcl"

cat > "$BACKEND_HCL" <<EOF
# Auto-generated by infra/ci/bootstrap-state.sh — do not commit (gitignored)
bucket         = "${BUCKET}"
key            = "netknife/dev/terraform.tfstate"
region         = "${REGION}"
dynamodb_table = "${TABLE}"
encrypt        = true
EOF
echo "Wrote ${BACKEND_HCL}"

echo ""
echo "=========================================="
echo "GitHub Actions secrets"
echo "=========================================="
echo "TF_STATE_BUCKET=${BUCKET}"
echo "TF_STATE_LOCK_TABLE=${TABLE}"
echo ""
echo "Next: migrate local state to S3"
echo "  cp infra/envs/dev/backend.tf.example infra/envs/dev/backend.tf"
echo "  cd infra/envs/dev && terraform init -backend-config=backend.hcl -migrate-state"
